# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables: 
  BuildConfiguration: 'release'
  # nombre del archivo csproj
  name-project: "trifenix.connect.mdm"
  folder: ""

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'AGROFENIX-mdm'
    scannerMode: 'MSBuild'
    projectKey: 'AGROFENIX-mdm'
    projectName: 'AGROFENIX-mdm'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '$(default-feed)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
  displayName: "build solution"
- task: SonarQubeAnalyze@4
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

- script: |      
    sudo apt install -y unzip
    wget https://scripts.trifenix.io/vsxmd/Vsxmd.$(vsxmd-version-production).zip
    unzip Vsxmd.$(vsxmd-version-production).zip -d ./vsxmd.$(vsxmd-version-production)    
    dotnet ./vsxmd.$(vsxmd-version-production)/Vsxmd.dll ./$(folder)$(name-project).xml nuget-packages
    git config --global user.email "alejandro.iglesias@trifenix.io"
    git config --global user.name "alejandro.iglesias"    
    git clone https://alejandro.iglesias:$(script-token)@github.com/trifenix/docs-trifenix-connect.git web
    cp -r ./$(folder)nuget-packages/* ./web/src/pages/nuget-packages
    cd ./web
    git add . && git commit -m 'nueva documentacion mdm' 
    git push origin master
  displayName: "publicando documentación"



